# Generated by Django 4.2.1 on 2023-09-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('question_status', models.CharField(choices=[('AC', 'Actual'), ('AR', 'Archive')], default='AC', max_length=2, verbose_name='Статус вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Voite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_voice', models.IntegerField(blank=True, default=0, verbose_name='ЗА')),
                ('negative_voice', models.IntegerField(blank=True, default=0, verbose_name='Против')),
                ('abstaned_voice', models.IntegerField(blank=True, default=0, verbose_name='Воздержалось')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voites', to='voiting.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голосы',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
