version: '3.9'

volumes:
  pg_data:


services:
  db:
    image: postgres:14.5
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - clickwork


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - clickwork


  worker:
    build: .
    command: sh -c "cd /code/api/ && celery -A ClickWork worker -l INFO"
    volumes:
      - .:/code
    depends_on:
      - web
      - db
      - redis
    networks:
      - clickwork

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSGRES_DB=${DB_NAME}
    command: python /code/api/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - clickwork

networks:
  clickwork:
    driver: bridge