# Generated by Django 4.2.1 on 2023-09-03 19:24

import app.user_docs.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='ИНН или персональный номер')),
                ('document', models.FileField(blank=True, upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'pdf'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .pdf .png'), app.user_docs.validators.document_size_validate], verbose_name='документ')),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=55, verbose_name='Серия и номер документа')),
                ('document_issued', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Когда и кем выдан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ юзера',
                'verbose_name_plural': 'Документы юзера',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bank_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес банка')),
                ('bank_bic', models.CharField(blank=True, max_length=55, null=True, verbose_name='БИК банка')),
                ('bank_correspondent_account', models.CharField(blank=True, max_length=55, null=True, verbose_name='Корреспондентский счет банка')),
                ('payment_account', models.CharField(blank=True, max_length=55, null=True, verbose_name='Расчетный счет')),
                ('recipients_name', models.CharField(blank=True, max_length=255, verbose_name='Имя получателя платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реквизит банка',
                'verbose_name_plural': 'Реквизиты банка',
            },
        ),
    ]
