# Generated by Django 4.2.1 on 2023-09-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_docs', '0002_region_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='document_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='document_issued',
            field=models.CharField(blank=True, max_length=255, verbose_name='Когда и кем выдан'),
        ),
    ]
