# Generated by Django 4.2.1 on 2023-09-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_docs', '0005_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoc',
            name='document_issued',
            field=models.CharField(max_length=255, verbose_name='Когда и кем выдан'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='document_name',
            field=models.CharField(default=15, max_length=100, verbose_name='Название документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=55, verbose_name='Серия или номер документа'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
