# Generated by Django 4.2.1 on 2023-10-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_docs', '0007_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор юзера', 'verbose_name_plural': 'Договоры юзеров'},
        ),
    ]
