# Generated by Django 4.2.1 on 2023-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_docs', '0009_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес банка'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка'),
        ),
    ]
