# Generated by Django 4.2.1 on 2023-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('text', models.TextField(max_length=1500, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('for_all', models.BooleanField(default=False, verbose_name='для всех')),
                ('for_freelancers', models.BooleanField(default=False, verbose_name='для фриласнеров')),
                ('for_customers', models.BooleanField(default=False, verbose_name='для заказчиков')),
                ('for_founders', models.BooleanField(default=False, verbose_name='для основателей')),
                ('slug', models.SlugField(max_length=255, unique_for_date='created')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['-created'], name='news_news_created_d2ca43_idx')],
            },
        ),
    ]
