# Generated by Django 4.2.1 on 2023-09-03 19:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=155, verbose_name='Название конкурса')),
                ('desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание конкурса')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена конкурса')),
                ('period', models.DateField(verbose_name='Срок риема работ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания конкурса')),
                ('completion_date', models.DateField(verbose_name='Дата выбора победителя')),
                ('slug', models.SlugField(max_length=120, unique_for_date='created_at')),
                ('views', models.IntegerField(default=0)),
                ('target_audience', models.TextField(blank=True, max_length=300, verbose_name='Целевая аудитория')),
                ('atention', models.TextField(blank=True, max_length=300, verbose_name='Обратить внимание')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
        migrations.CreateModel(
            name='ContestAppFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contets_files/%Y/%m%d', verbose_name='')),
            ],
            options={
                'verbose_name': 'Файл кокурса',
                'verbose_name_plural': 'Файлы конкурса',
            },
        ),
        migrations.CreateModel(
            name='ContestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_status', models.CharField(choices=[('NS', 'No_Status'), ('CN', 'Candidate'), ('EX', 'Executor')], default='NS', max_length=2, verbose_name='')),
                ('executor_place', models.CharField(choices=[('NP', 'No_place'), ('FP', 'First_place'), ('SC', 'Second_place'), ('TP', 'Third_place')], default='NP', max_length=2, verbose_name='')),
                ('desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('file1', models.FileField(blank=True, null=True, upload_to='contest_files/responses/%Y/%m/%d', verbose_name='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='contest_files/responses/%Y/%m/%d', verbose_name='')),
                ('file3', models.FileField(blank=True, null=True, upload_to='contest_files/responses/%Y/%m/%d', verbose_name='')),
            ],
            options={
                'verbose_name': 'Отклик на конкурс',
                'verbose_name_plural': 'Отклики на конкурсы',
            },
        ),
        migrations.CreateModel(
            name='ContestResponseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('file1', models.FileField(blank=True, null=True, upload_to='contest_response_comments/%Y/%m/%d', verbose_name='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='contest_response_comments/%Y/%m/%d', verbose_name='')),
                ('file3', models.FileField(blank=True, null=True, upload_to='contest_response_comments/%Y/%m/%d', verbose_name='')),
                ('contest_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_response_comments', to='contests.contestresponse', verbose_name='')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_replies', to='contests.contestresponsecomment', verbose_name='')),
            ],
            options={
                'verbose_name': 'Комметрий отклика',
                'verbose_name_plural': 'Комментарии отклика',
            },
        ),
    ]
