# Generated by Django 4.2.1 on 2023-09-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_docs', '0002_region_country'),
        ('main_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_countries', to='user_docs.country'),
            preserve_default=False,
        ),
    ]
