# Generated by Django 4.2.1 on 2023-09-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0003_alter_userinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='polzunok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfocompany',
            name='employee_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность представитля'),
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='main_users.userinfo'),
        ),
    ]
