# Generated by Django 4.2.1 on 2023-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0004_userinfo_polzunok_userinfocompany_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfocompany',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Полное название компании'),
        ),
    ]
