# Generated by Django 4.2.1 on 2023-09-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0005_alter_userinfocompany_ceo_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='experiense',
            new_name='experience',
        ),
    ]
