# Generated by Django 4.2.1 on 2023-09-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0007_delete_userinfocompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность представитля')),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Полное название компании')),
                ('short_company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название компании')),
                ('ceo_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО руководителя')),
                ('ceo_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя')),
                ('adress_in_law', models.CharField(blank=True, max_length=200, null=True, verbose_name='Юр. адрес')),
                ('adress_fact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Физ. адрес')),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН')),
                ('company_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН')),
                ('kpp_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='КПП')),
                ('certificate', models.CharField(blank=True, max_length=30, null=True, verbose_name='Свидетельство номер')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='company_docs/%Y/%m/%d', verbose_name='Свидетельство файл')),
                ('company_site', models.CharField(blank=True, max_length=80, null=True, verbose_name='Сайт компании')),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон компании')),
                ('company_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email компании')),
                ('social_site', models.CharField(blank=True, max_length=80, null=True, verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='main_users.userinfocompany'),
        ),
    ]
