# Generated by Django 4.2.1 on 2023-09-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_docs', '0006_alter_userdoc_document_issued_and_more'),
        ('main_users', '0008_userinfocompany_userinfo_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfocompany',
            options={'verbose_name': 'Компания Пользователя', 'verbose_name_plural': 'Компании Пользователей'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='experience',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='adress',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес проживания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_countries', to='user_docs.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(default='1987-09-29', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(max_length=155, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(db_index=True, default=4, max_length=155, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='on_vacation',
            field=models.BooleanField(default=False, verbose_name='Отпуск'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default=5, max_length=30, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='adress_fact',
            field=models.CharField(default=6, max_length=200, verbose_name='Физ. адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='adress_in_law',
            field=models.CharField(default=7, max_length=200, verbose_name='Юр. адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='ceo_name',
            field=models.CharField(default=8, max_length=150, verbose_name='ФИО руководителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='certificate_file',
            field=models.FileField(default=9, upload_to='company_docs/%Y/%m/%d', verbose_name='Свидетельство файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='company_email',
            field=models.CharField(default=1, max_length=50, verbose_name='Email компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='company_name',
            field=models.CharField(db_index=True, default=8, max_length=100, verbose_name='Полное название компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='company_phone',
            field=models.CharField(default=9, max_length=30, verbose_name='Телефон компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='employee_position',
            field=models.CharField(default=8, max_length=100, verbose_name='Должность представитля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='reg_number',
            field=models.CharField(default=8, max_length=50, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfocompany',
            name='short_company_name',
            field=models.CharField(default=7, max_length=100, verbose_name='Короткое название компании'),
            preserve_default=False,
        ),
    ]
