# Generated by Django 4.2.1 on 2023-09-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0008_userinfocompany_userinfo_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfocompany',
            options={'verbose_name': 'Компания Пользователя', 'verbose_name_plural': 'Компании Пользователей'},
        ),
    ]
