# Generated by Django 4.2.1 on 2023-09-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0009_alter_userinfocompany_options'),
        ('main_users', '0009_alter_userinfocompany_options_and_more'),
    ]

    operations = [
    ]
