# Generated by Django 4.2.1 on 2023-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0010_merge_20230922_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Стаж:'),
        ),
    ]
