# Generated by Django 4.2.1 on 2023-10-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0011_userinfo_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfocompany',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_info_company', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
