# Generated by Django 4.2.1 on 2023-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0012_userinfocompany_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfocompany',
            name='user',
        ),
    ]
