# Generated by Django 4.2.1 on 2023-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_users', '0013_remove_userinfocompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('RUB', 'Р'), ('EUR', '€')], max_length=3, null=True, verbose_name='Валюта стоимости часа работ'),
        ),
    ]
