# Generated by Django 4.2.1 on 2023-10-29 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='TinkofPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_acc', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(default='', max_length=150)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Оплата Тинькоф',
                'verbose_name_plural': 'Оплаты через Тинькоф',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalEcurrencyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('cryptoCurrencyAmount', models.FloatField(null=True, verbose_name='Сумма транзакции в криптовалюте')),
                ('currency', models.CharField(max_length=5, verbose_name='Валюта')),
                ('ecurrency', models.CharField(max_length=15, verbose_name='Электронная валюта')),
                ('receiver', models.CharField(max_length=1024, verbose_name='Получатель')),
                ('destinationTag', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Тег Ripple')),
                ('orderId', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Идентификатор в системе учета пользователя')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание для транзакции')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ecurrency_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_ecurrency_transactions', to='accounts.account', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Вывод средств в стороннюю платежную систему',
                'verbose_name_plural': 'Выводы средств в стороннюю платежную систему',
                'db_table': 'adv_cash__to_crypto_transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('bank_card', models.CharField(max_length=155, verbose_name='Номер карты')),
                ('expiry_month', models.IntegerField(verbose_name='Месяц истечения')),
                ('expiry_year', models.IntegerField(verbose_name='Год истечения')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание для транзакции')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions', to='accounts.account', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Транзакция вывода на банк счет',
                'verbose_name_plural': 'Транзакции вывода на банк счет',
                'db_table': 'adv_cash__transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Метод оплаты')),
                ('comission', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Комиссия')),
                ('currency', models.ManyToManyField(related_name='currencies', to='adv_cash.currency')),
            ],
            options={
                'verbose_name': 'Способ платежа',
                'verbose_name_plural': 'Способы платежей',
            },
        ),
        migrations.CreateModel(
            name='PaymentAgregator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Агрегатор платежа')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agregator_accounts', to='accounts.account')),
                ('method', models.ManyToManyField(related_name='methods', to='adv_cash.paymentmethod')),
            ],
            options={
                'verbose_name': 'Агрегатор Платежа',
                'verbose_name_plural': 'Агрегаторы платежей',
            },
        ),
    ]
