# Generated by Django 4.2.1 on 2023-11-03 05:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adv_cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListTransactionsHash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('ac_hash', models.CharField(verbose_name='Хеш')),
            ],
        ),
    ]
