# Generated by Django 4.2.1 on 2023-09-03 19:24

import app.portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('desc', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компании',
            },
        ),
        migrations.CreateModel(
            name='ReferalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('work_links', models.TextField(blank=True, max_length=400)),
                ('file1', models.FileField(blank=True, null=True, upload_to='get_referal_link/%Y/%m/%d', validators=[app.portfolio.validators.file_size_validate])),
                ('file2', models.FileField(blank=True, null=True, upload_to='get_referal_link/%Y/%m/%d', validators=[app.portfolio.validators.file_size_validate])),
                ('file3', models.FileField(blank=True, null=True, upload_to='get_referal_link/%Y/%m/%d', validators=[app.portfolio.validators.file_size_validate])),
                ('file4', models.FileField(blank=True, null=True, upload_to='get_referal_link/%Y/%m/%d', validators=[app.portfolio.validators.file_size_validate])),
                ('file5', models.FileField(blank=True, null=True, upload_to='get_referal_link/%Y/%m/%d', validators=[app.portfolio.validators.file_size_validate])),
            ],
            options={
                'verbose_name': 'Получатель реф ссылки',
                'verbose_name_plural': 'Получатели реф ссылки',
            },
        ),
    ]
