# Generated by Django 4.2.1 on 2023-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_doc',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
