# Generated by Django 4.2.1 on 2023-09-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderresponse_created_at'),
        ('portfolio', '0002_remove_work_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWork',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.work')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='выполненный заказ')),
            ],
            options={
                'verbose_name': 'текущая работа',
                'verbose_name_plural': 'текущие работы',
                'ordering': ['-created_at'],
            },
            bases=('portfolio.work',),
        ),
    ]
