# Generated by Django 4.2.1 on 2023-09-24 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_currentwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="time_spend",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Потраченное время в часах",
            ),
        ),
    ]
