# Generated by Django 4.2.1 on 2023-09-24 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_work_time_spend"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="place",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Место в таблице",
            ),
        ),
    ]
