# Generated by Django 4.2.1 on 2023-09-24 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_work_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="place",
        ),
        migrations.AddField(
            model_name="work",
            name="table_place",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Место в таблице",
            ),
        ),
    ]
