# Generated by Django 4.2.1 on 2023-10-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_work_place_work_table_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='table_place',
        ),
        migrations.RemoveField(
            model_name='work',
            name='time_spend',
        ),
    ]
