# Generated by Django 4.2.1 on 2023-10-13 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_work_place_work_table_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='table_place',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Место в таблице'),
        ),
    ]
