# Generated by Django 4.2.1 on 2023-10-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_work_time_spend'),
        ('portfolio', '0008_work_table_place_work_time_spend'),
    ]

    operations = [
    ]
