# Generated by Django 4.2.1 on 2023-10-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_merge_20231015_2054'),
        ('portfolio', '0009_merge_20231015_2115'),
    ]

    operations = [
    ]
