# Generated by Django 4.2.1 on 2023-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта адресата:')),
                ('type_of_notifications', models.CharField(choices=[('chat', 'chat'), ('news', 'news'), ('votes', 'votes'), ('reviews', 'reviews'), ('fr_responses', 'Responses from freelancers'), ('cs_responses', 'Responses from customers'), ('refill', 'Account refill')], verbose_name='Тип уведомлений:')),
                ('template', models.TextField(max_length=10000, verbose_name='Шаблон для отправки сообщения:')),
                ('title', models.TextField(max_length=150, verbose_name='Тема сообщения:')),
            ],
        ),
    ]
