# Generated by Django 4.2.1 on 2023-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта адресата:'),
        ),
    ]
