# Generated by Django 4.2.1 on 2023-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_remove_notification_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.JSONField(blank=True, null=True, verbose_name='Контекст для темплейта:'),
        ),
    ]
