# Generated by Django 4.2.1 on 2023-09-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('PT', 'Positive'), ('NT', 'Negative')], default='PT', max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
