# Generated by Django 4.2.1 on 2023-09-23 13:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderresponse_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderresponsecomment',
            options={'verbose_name': 'Комментарий к отклику', 'verbose_name_plural': 'Комментарии к откликам'},
        ),
    ]
