# Generated by Django 4.2.1 on 2023-09-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.IntegerField(verbose_name='Время пошедшее с момента регистрации')),
                ('orders', models.IntegerField()),
                ('world_orders', models.IntegerField()),
                ('arbit', models.IntegerField()),
                ('contest', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('reply_time', models.IntegerField()),
                ('vote_participation', models.IntegerField()),
                ('freelancer', models.OneToOneField(help_text='выберите подходящий user instance', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Фрилансер:')),
            ],
        ),
    ]
