# Generated by Django 4.2.1 on 2023-09-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0002_alter_rating_arbit_alter_rating_contest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='arbit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='contest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='orders',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reg_time',
            field=models.IntegerField(null=True, verbose_name='Время пошедшее с момента регистрации'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote_participation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='world_orders',
            field=models.IntegerField(null=True),
        ),
    ]
