# Generated by Django 4.2.1 on 2023-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0003_alter_rating_arbit_alter_rating_contest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaitingCalculateConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('peace_orders', models.IntegerField()),
                ('arbit', models.IntegerField()),
                ('contest', models.IntegerField()),
                ('wins_1_place', models.IntegerField()),
                ('wins_2_place', models.IntegerField()),
                ('wins_3_place', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('reply_time_1_hour', models.IntegerField()),
                ('reply_time_6_hour', models.IntegerField()),
                ('reply_time_more', models.IntegerField()),
                ('vote_participation', models.IntegerField()),
                ('vote_ignore', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='world_orders',
            new_name='peace_orders',
        ),
    ]
