# Generated by Django 4.2.1 on 2023-09-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0004_raitingcalculateconstant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaitingCalculateConstant',
            new_name='RatingCalculateConstant',
        ),
    ]
