# Generated by Django 4.2.1 on 2023-09-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0006_rename_reviews_ratingcalculateconstant_review_negative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingcalculateconstant',
            old_name='review_postive',
            new_name='review_positive',
        ),
    ]
