# Generated by Django 4.2.1 on 2023-09-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0008_alter_rating_arbit_alter_rating_contest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='contest',
        ),
    ]
