# Generated by Django 4.2.1 on 2023-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0009_remove_rating_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='contest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
