# Generated by Django 4.2.1 on 2023-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0011_alter_rating_arbit_alter_rating_contest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='summary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итого:'),
        ),
    ]
