# Generated by Django 4.2.1 on 2023-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0013_remove_rating_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='arbit',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Кол-во арбитражей:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='contest',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Кол-во учрежденных или посещенных контестов:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='orders',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Кол-во заказов:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='peace_orders',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Кол-во мировых соглашений:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reg_time',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Время пошедшее с момента регистрации'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_time',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Продолжительность ответа на оффер:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Кол-во отзывов:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote_participation',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Участие в голосованиях:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wins',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', null=True, verbose_name='Кол-во побед в контестах:'),
        ),
    ]
