# Generated by Django 4.2.1 on 2023-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0014_alter_rating_arbit_alter_rating_contest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reply_time_1_hour_value',
            field=models.IntegerField(default=1, verbose_name='Ответ на оффер в течение часа:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='reply_time_6_hour_value',
            field=models.IntegerField(default=1, verbose_name='Ответ на оффер в течение 6 часов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='reply_time_more_value',
            field=models.IntegerField(default=1, verbose_name='Ответ на оффер ≥12 часов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='review_negative_value',
            field=models.IntegerField(default=1, verbose_name='Негативный отзыв:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='review_positive_value',
            field=models.IntegerField(default=1, verbose_name='Позитивный отзыв:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='vote_ignore_value',
            field=models.IntegerField(default=1, verbose_name='Игнор голосования:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='vote_participation_value',
            field=models.IntegerField(default=1, verbose_name='Участие в голосовании:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='wins_1_place_value',
            field=models.IntegerField(default=1, verbose_name='Победа в контесте:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='wins_2_place_value',
            field=models.IntegerField(default=1, verbose_name='Второе место в контесте:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='wins_3_place_value',
            field=models.IntegerField(default=1, verbose_name='Третье место в контесте:'),
            preserve_default=False,
        ),
    ]
