# Generated by Django 4.2.1 on 2023-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0015_rating_reply_time_1_hour_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='arbit',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Кол-во арбитражей:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='contest',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Кол-во учрежденных или посещенных контестов:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='orders',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Кол-во заказов:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='peace_orders',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Кол-во мировых соглашений:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reg_time',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Время пошедшее с момента регистрации'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_time',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Продолжительность ответа на оффер:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_time_1_hour_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ответ на оффер в течение часа:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_time_6_hour_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ответ на оффер в течение 6 часов'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_time_more_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ответ на оффер ≥12 часов'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review_negative_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Негативный отзыв:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review_positive_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Позитивный отзыв:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Кол-во отзывов:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote_ignore_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Игнор голосования:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote_participation',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Участие в голосованиях:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote_participation_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Участие в голосовании:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wins',
            field=models.IntegerField(blank=True, default=0, help_text='поле можно оставить пустым', verbose_name='Кол-во побед в контестах:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wins_1_place_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Победа в контесте:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wins_2_place_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Второе место в контесте:'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wins_3_place_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Третье место в контесте:'),
        ),
    ]
