# Generated by Django 4.2.1 on 2023-10-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название чат комнаты:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комнаты:')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_1', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1:')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2:')),
            ],
            options={
                'verbose_name': 'Чат комната',
                'verbose_name_plural': 'Чат комнаты',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема:')),
                ('text', models.CharField(max_length=400, verbose_name='Текст обсуждения:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания треда:')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='Создатель:')),
            ],
            options={
                'verbose_name': 'Тред',
                'verbose_name_plural': 'Треды',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=600, verbose_name='Текст сообщения:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки сообщения:')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Комната:')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Текст комментария:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария:')),
                ('comment', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='chat.comment', verbose_name='Главный комментарий:')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор:')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.thread', verbose_name='Тред:')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
