# Generated by Django 4.2.1 on 2023-10-13 08:58

import app.portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files/None/', validators=[app.portfolio.validators.file_size_validate], verbose_name='файл'),
        ),
    ]
