# Generated by Django 4.2.1 on 2023-10-13 09:20

import app.chat.models
import app.portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.chat.models.room_name, validators=[app.portfolio.validators.file_size_validate], verbose_name='файл'),
        ),
    ]
