# Generated by Django 4.2.1 on 2023-09-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='purpose_of_payment',
            field=models.CharField(choices=[('Entry Fee', 'Вступительный взнос пользователя'), ('Referal Program', 'Реферальные бонусы'), ('No Demand', 'Не востребованный платеж'), ('Create Order', 'Создание заказа')], max_length=20, verbose_name='назначение платежа'),
        ),
    ]
