# Generated by Django 4.2.1 on 2023-09-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_operation_purpose_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='summ',
            new_name='value',
        ),
    ]
