# Generated by Django 4.2.1 on 2023-10-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_operation_purpose_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='purpose_of_payment',
            field=models.CharField(max_length=100, verbose_name='назначение платежа'),
        ),
    ]
