# Generated by Django 4.2.1 on 2023-10-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=18, unique=True, verbose_name='Cчёт'),
        ),
    ]
