schema:
	python manage.py spectacular --color --file schema.yml

run:
	python manage.py runserver


mm:
	python manage.py makemigrations

mi:
	python manage.py migrate

cel:
	celery -A ClickWork worker --loglevel=info